"""PBuddy work-breakdown structure: the backlog as data.

Edit this file and run ``python3 tools/jira_sync.py`` to push to Jira. Each item:
  code     stable WBS id (drives idempotent upsert via a code:<id> label)
  summary  issue title
  status   To Do | In Progress | In Review | Done
  context  why this exists
  ac       acceptance criteria — written to be testable
  verify   how to verify (command / manual step)
  refs     file paths / artefacts (for done or in-progress work)
"""

EPICS = [
    # =====================================================================
    {
        "code": "E1",
        "summary": "Foundations & Infrastructure (Phase 0)",
        "status": "In Progress",
        "context": "Stand up the monorepo, cloud project, and developer workflow so every "
                   "later phase is reproducible: one Expo codebase (iOS/Android/web), a "
                   "Cloud Run API, Postgres migrations, and GCP+Firebase wiring.",
        "ac": [
            "Monorepo builds and tests run from the repo root.",
            "GCP project pbuddy-mvp is connected with Firebase phone auth enabled.",
            "GitHub repo is synced with push/pull working.",
        ],
        "children": [
            {
                "code": "E1-S1", "summary": "Monorepo scaffold (api/app/db/infra)", "status": "Done",
                "context": "Workspace layout with api (Cloud Run), app (Expo), db (migrations), infra (GCP).",
                "ac": ["npm workspaces resolve", "api/app/db/infra directories exist",
                       "root scripts (api:test, db:migrate) defined"],
                "verify": "npm install at root succeeds; npm run api:test runs.",
                "refs": ["package.json", "README.md", ".gitignore"],
            },
            {
                "code": "E1-S2", "summary": "Postgres schema + forward-only migration runner", "status": "Done",
                "context": "Relational schema (money in pence) plus an idempotent migration runner.",
                "ac": ["0001_init.sql + 0002_seed.sql apply cleanly",
                       "migrate.mjs tracks applied files in schema_migrations",
                       "corridor allowlist + versioned legal_copy seeded"],
                "verify": "DATABASE_URL=... npm run db:migrate applies both migrations.",
                "refs": ["db/migrations/0001_init.sql", "db/migrations/0002_seed.sql", "db/migrate.mjs"],
            },
            {
                "code": "E1-S3", "summary": "GCP + Firebase wiring (pbuddy-mvp)", "status": "Done",
                "context": "Connect the repo to the live GCP/Firebase project, enable phone auth, lock Firestore.",
                "ac": ["Project pbuddy-mvp active; required APIs enabled",
                       "Firebase phone sign-in enabled",
                       "Firestore security rules deployed (read-only status mirror, server-only writes)",
                       "Web SDK config wired into the client"],
                "verify": "Admin config shows signIn.phoneNumber.enabled=true; firebase deploy --only firestore:rules succeeds.",
                "refs": [".firebaserc", "firebase.json", "firestore.rules", "app/firebaseConfig.ts"],
            },
            {
                "code": "E1-S4", "summary": "GitHub repo + credential sync", "status": "Done",
                "context": "Initialise git, connect origin, keep push/pull synced without leaking the PAT.",
                "ac": ["origin = github.com/khanwaseemraza/pbuddy with clean URL (no token)",
                       "credentials stored outside the repo; .env and secrets gitignored",
                       "main pushed and tracking origin/main"],
                "verify": "git push / git fetch work; git status clean; no secrets in tracked files.",
                "refs": ["~/.pbuddy-git-credentials (outside repo)"],
            },
            {
                "code": "E1-S5", "summary": "CI pipeline (tests + framing lint + typecheck)", "status": "To Do",
                "context": "GitHub Actions running unit tests, the framing banned-word lint, and tsc on every PR.",
                "ac": ["Workflow runs npm test, lint:framing, typecheck on push/PR",
                       "DB-gated integration tests run against an ephemeral Postgres service",
                       "Red build blocks merge"],
                "verify": "Open a PR; checks appear and pass/fail correctly.",
            },
            {
                "code": "E1-S6", "summary": "Cloud Run + Cloud SQL provisioning (deferred)", "status": "To Do",
                "context": "Provision Cloud SQL (Postgres) and deploy the API to Cloud Run via Cloud Build. "
                           "Deferred per cost decision; everything is pre-wired.",
                "ac": ["Cloud SQL instance + DB created; migrations applied",
                       "API deployed to Cloud Run with Cloud SQL connector + secrets",
                       "Region co-located with Firestore (europe-west2) decision recorded"],
                "verify": "gcloud builds submit --config infra/cloudbuild.yaml deploys; /readyz returns ready.",
                "refs": ["infra/Dockerfile", "infra/cloudbuild.yaml"],
            },
        ],
    },
    # =====================================================================
    {
        "code": "E2",
        "summary": "Compliance & Cost-Sharing Firewall (legal-as-code)",
        "status": "In Progress",
        "context": "PBuddy's legal survival depends on staying a cost-sharing / expense-reimbursement "
                   "platform, never hire & reward. These rules are enforced as DB-level invariants and "
                   "server-side checks, with an immutable audit trail — not buried in T&Cs.",
        "ac": [
            "A traveller can never accept contributions exceeding their own journey cost.",
            "A student-visa user can never become Pro Buddy.",
            "Every legally-relevant decision is recorded in an append-only audit log.",
        ],
        "children": [
            {
                "code": "E2-S1", "summary": "Capacity ledger with committed<=cap invariant", "status": "Done",
                "context": "Per-trip ledger; the cost-sharing invariant is a DB CHECK constraint.",
                "ac": ["trip_capacity_ledger created per trip with cap = locked journey cost",
                       "CHECK (committed_pennies <= cap_pennies) rejects over-commit",
                       "remaining_pennies is a generated column (cannot drift)"],
                "verify": "Integration test: direct UPDATE over cap is rejected by the constraint.",
                "refs": ["db/migrations/0001_init.sql", "api/test/firewall.integration.test.ts"],
            },
            {
                "code": "E2-S2", "summary": "evaluateCap + atomic reserveCapacity (concurrency-safe)", "status": "Done",
                "context": "Pure cap decision + row-locked reservation so concurrent accepts serialize.",
                "ac": ["evaluateCap rejects contributions that breach the cap (incl. cumulative)",
                       "reserveCapacity locks the ledger row (FOR UPDATE) before committing",
                       "Concurrent accepts on one trip can never exceed the cap"],
                "verify": "npm run api:test (unit) + concurrent-accept integration test asserts exactly one succeeds.",
                "refs": ["api/src/services/caps.ts", "api/test/caps.test.ts", "api/src/db.ts"],
            },
            {
                "code": "E2-S3", "summary": "Cap-bounded bidding enforcement (place + accept)", "status": "Done",
                "context": "Bids are validated against the cap at creation and re-validated atomically at accept.",
                "ac": ["A bid above sender max or above remaining cap is rejected",
                       "Accept reserves capacity atomically and creates the booking",
                       "Competing bids on the parcel expire on accept"],
                "verify": "Place a bid over cap -> 409 cap_exceeded; accept under cap -> 201 booking.",
                "refs": ["api/src/routes/bids.ts"],
            },
            {
                "code": "E2-S4", "summary": "Trip-frequency throttle (incidental-traveller bounds)", "status": "Done",
                "context": "Cap trips/week (global + per route) so Casual users look like travellers, not couriers; "
                           "hitting the ceiling flags a Pro Buddy upgrade signal.",
                "ac": ["evaluateFrequency blocks at weekly/route/monthly ceilings",
                       "Blocked publish returns an upgrade signal for eligible non-students",
                       "Counters persisted in user_trip_counters and enforced at trip publish"],
                "verify": "Unit tests pass; publishing past the weekly limit is blocked (route handler TBD).",
                "refs": ["api/src/services/frequency.ts", "api/test/caps.test.ts"],
            },
            {
                "code": "E2-S5", "summary": "Two-tier model: Casual/Pro DB constraints", "status": "Done",
                "context": "Casual Buddy = safe harbour; Pro Buddy = uncapped but gated by RTW + hire&reward.",
                "ac": ["CHECK students_cannot_be_pro blocks student_visa + pro_buddy",
                       "CHECK pro_requires_rtw blocks pro_buddy without verified RTW",
                       "proBypassAllowed() bypasses the cap only when gates are satisfied"],
                "verify": "Integration test: inserting a student-visa Pro user is rejected; proBypass unit tests pass.",
                "refs": ["db/migrations/0001_init.sql", "api/src/services/caps.ts"],
            },
            {
                "code": "E2-S6", "summary": "Append-only hash-chained compliance audit log", "status": "Done",
                "context": "Tamper-evident evidence trail for HMRC / Home Office / insurers.",
                "ac": ["Each row hash-chains to the previous (prev_hash/row_hash)",
                       "UPDATE/DELETE are forbidden by trigger",
                       "writeAudit() records CAP_CHECK etc. inside the same transaction"],
                "verify": "Integration test: UPDATE on compliance_audit_log raises 'append-only'.",
                "refs": ["db/migrations/0001_init.sql", "api/src/lib/audit.ts"],
            },
            {
                "code": "E2-S7", "summary": "Framing lint + versioned legal copy", "status": "Done",
                "context": "Never call a contribution a 'fee'/'earnings' on the user-facing path.",
                "ac": ["banned-words lint fails CI on banned terms in user-facing strings",
                       "Internal revenue terms (platform_fee/escrow_fee) are allowlisted",
                       "legal_copy table holds versioned framing strings"],
                "verify": "node api/scripts/banned-words.mjs prints 'framing lint clean'.",
                "refs": ["api/scripts/banned-words.mjs", "db/migrations/0002_seed.sql"],
            },
            {
                "code": "E2-S8", "summary": "Open-box gate (pickup blocked without inspection)", "status": "Done",
                "context": "Traveller must inspect unsealed contents before escrow arms.",
                "ac": ["A booking cannot reach picked_up without an open_box_confirmed event",
                       "Enforced by DB trigger as the structural backstop"],
                "verify": "Attempt to set status=picked_up with no open-box event -> exception.",
                "refs": ["db/migrations/0001_init.sql"],
            },
            {
                "code": "E2-S9", "summary": "Domestic-only allowlist + GB postcode validation", "status": "Done",
                "context": "Corridors are a curated UK allowlist; pickup/dropoff postcodes validated GB via postcodes.io.",
                "ac": ["No international route can be created (none exist in the table)",
                       "Both pickup and dropoff resolve to valid GB postcodes",
                       "ROUTE_VALIDATED audit event written"],
                "verify": "Posting a non-GB postcode is rejected; valid postcode resolves to lat/lng.",
            },
            {
                "code": "E2-S11", "summary": "User provisioning + real Firebase token verification", "status": "Done",
                "context": "The auth middleware verifies a Firebase ID token but requires the users row to "
                           "already exist (403 user_not_provisioned). Add token verification without a service "
                           "account (verifyIdToken needs only the project id) and a POST /users/me that "
                           "auto-creates the user from the verified token, so the app can make authenticated calls.",
                "ac": ["API verifies real Firebase ID tokens (no ADC/service-account needed; project id only)",
                       "POST /users/me upserts the user from the verified token (uid + phone)",
                       "Authenticated endpoints work after first provisioning; dev-bypass still works for tests"],
                "verify": "Sign in on web -> app provisions the user -> /corridors loads. Integration test covers upsert.",
                "refs": ["api/src/middleware/auth.ts", "api/src/lib/firebase.ts", "api/src/routes/users.ts"],
            },
            {
                "code": "E2-S10", "summary": "Compliance evidence exports (HMRC/Home Office/insurer)", "status": "Done",
                "context": "First-class reports from the audit log proving the rules were enforced.",
                "ac": ["Per-user annual gross contribution + cap-enforcement export (HMRC)",
                       "Per-student Tier-1 lock + reimbursement-only export (Home Office)",
                       "Route/mode/open-box/prohibited-items export (insurer)"],
                "verify": "Export endpoints return correct aggregates for seeded data.",
            },
        ],
    },
    # =====================================================================
    {
        "code": "E3",
        "summary": "Marketplace Core: Matching & Bidding (Phase 1)",
        "status": "In Progress",
        "context": "The two-sided marketplace: post trips/parcels, match them, and run cap-bounded "
                   "price discovery (reverse auction) that can never breach the cost-sharing invariant.",
        "ac": [
            "Senders post parcels with real addresses; travellers post trips.",
            "Matching surfaces only cap-valid, in-corridor, fitting candidates.",
            "Bidding produces a booking without breaching the cap.",
        ],
        "children": [
            {
                "code": "E3-S1", "summary": "Trips: create with locked journey cost + ledger init", "status": "Done",
                "context": "Journey cost is captured and locked at creation; the ledger is auto-created by trigger.",
                "ac": ["Trip stores journey_cost + source + cost_locked_at",
                       "trip_capacity_ledger row auto-created with cap = journey cost"],
                "verify": "Integration test: ledger auto-created with cap = journey cost.",
                "refs": ["db/migrations/0001_init.sql"],
            },
            {
                "code": "E3-S2", "summary": "Parcels: post with real addresses + value/dimension caps", "status": "Done",
                "context": "Sender posts a parcel with GB pickup/dropoff addresses, size/value within caps, pricing mode.",
                "ac": ["declared_value <= configured cap; dimensions <= 100cm; piece_count 1..3",
                       "pickup/dropoff postcode+address+lat/lng stored",
                       "pricing_mode fixed/auction with suggested/max contribution"],
                "verify": "POST parcel persists addresses; over-cap value/dimension rejected (schema done; route TBD).",
                "refs": ["db/migrations/0001_init.sql"],
            },
            {
                "code": "E3-S3", "summary": "Matching engine: candidates + proximity/trust ranking", "status": "Done",
                "context": "SQL hard filters + Haversine proximity + trust scoring (no ML for MVP).",
                "ac": ["Filters: same corridor+direction, KYC-verified, window overlap, cap-affordable, fits luggage",
                       "Ranking prefers higher contribution + closer detour + more trusted sender"],
                "verify": "Unit test rankForTraveler orders near-rich above far-cheap; GET /trips/:id/matches.",
                "refs": ["api/src/services/matching.ts", "api/src/routes/matching.ts", "api/test/caps.test.ts"],
            },
            {
                "code": "E3-S4", "summary": "Bids API: place + accept (booking creation)", "status": "Done",
                "context": "Travellers bid; senders accept; booking created atomically with cap reservation.",
                "ac": ["POST /parcels/:id/bids validates cap + sender max + luggage",
                       "POST /bids/:id/accept creates booking, expires competing bids, marks parcel matched"],
                "verify": "Manual: place + accept flow returns booking_id; competing bids expire.",
                "refs": ["api/src/routes/bids.ts"],
            },
            {
                "code": "E3-S5", "summary": "Price suggestion (cold-start helper)", "status": "Done",
                "context": "Size-band x distance-band suggested contribution, clamped to the cap, to anchor senders.",
                "ac": ["Suggested contribution computed from bands and never exceeds the cap",
                       "Surfaced on the post-parcel form"],
                "verify": "Suggestion endpoint returns a sane, capped value for given size/distance.",
            },
            {
                "code": "E3-S6", "summary": "Booking lifecycle + Firestore status mirror", "status": "Done",
                "context": "Drive booking states and mirror status to Firestore for live client updates.",
                "ac": ["Lifecycle transitions enforced server-side",
                       "Each transition writes a booking_status doc readable only by participants",
                       "FCM push on key transitions"],
                "verify": "Client subscribed to booking_status sees updates; non-participants are denied.",
            },
        ],
    },
    # =====================================================================
    {
        "code": "E4",
        "summary": "Payments & Identity: Escrow + KYC (Phase 2)",
        "status": "To Do",
        "context": "Stripe Connect escrow via manual capture + Stripe Identity KYC. The riskiest block — "
                   "money moves only server-side in response to signed webhooks.",
        "ac": ["Funds authorized at funding, captured at pickup, transferred at dropoff.",
               "Both sides KYC-verified before transacting.",
               "Refunds and reconciliation work end-to-end in Stripe test mode."],
        "children": [
            {"code": "E4-S1", "summary": "Stripe Connect Express onboarding (travellers)", "status": "Done",
             "context": "Travellers onboard as payees; Stripe runs payee KYC/AML.",
             "ac": ["Connect Express account created + linked to user", "Payout-ready status tracked"],
             "verify": "Onboarding link completes; stripe_connect_id stored."},
            {"code": "E4-S2", "summary": "Stripe Identity KYC (both sides)", "status": "Done",
             "context": "Verify sender + traveller identity before they can transact.",
             "ac": ["KYC session created; webhook flips users.kyc_status", "Posting/claiming blocked until verified"],
             "verify": "Test-mode verification flips kyc_status to verified."},
            {"code": "E4-S3", "summary": "Manual-capture funding (authorize)", "status": "Done",
             "context": "Sender funds escrow: authorize full amount (capture_method=manual).",
             "ac": ["PaymentIntent authorized; payment row state=authorized", "Itemized: contribution + £1.50 + insurance"],
             "verify": "Funding authorizes a test card; ledger row created."},
            {"code": "E4-S4", "summary": "Capture on pickup, transfer on dropoff", "status": "Done",
             "context": "Capture funds on pickup scan; transfer payout to traveller on dropoff scan.",
             "ac": ["Pickup scan captures the intent (state=captured)", "Dropoff scan transfers payout (state=released)"],
             "verify": "Test-mode end-to-end: authorize -> capture -> transfer."},
            {"code": "E4-S5", "summary": "Refunds & partial refunds", "status": "Done",
             "context": "Cancel uncaptured / refund captured / admin split on dispute.",
             "ac": ["Uncaptured cancel releases hold", "Captured refund + partial split supported"],
             "verify": "Dispute paths produce correct Stripe refunds."},
            {"code": "E4-S6", "summary": "Reconciliation: ledger vs Stripe", "status": "Done",
             "context": "Reconcile internal payment ledger against Stripe balance/transactions.",
             "ac": ["Daily reconciliation report flags mismatches"],
             "verify": "Seeded transactions reconcile cleanly."},
        ],
    },
    # =====================================================================
    {
        "code": "E5",
        "summary": "Hand-off & Trust (Phase 3)",
        "status": "To Do",
        "context": "Secure QR/OTP hand-off at pickup and dropoff, the open-box inspection step, and ratings "
                   "feeding a trust score.",
        "ac": ["Pickup/dropoff confirmed by QR (OTP fallback).",
               "Open-box inspection required before pickup.",
               "Ratings update a visible trust score."],
        "children": [
            {"code": "E5-S1", "summary": "QR token generation + scanner", "status": "Done",
             "context": "Single-use QR tokens shown by one party, scanned by the other.",
             "ac": ["Pickup/dropoff QR tokens generated per booking", "Scan validates token + logs handoff_event"],
             "verify": "Scanning a valid token advances the booking; reused token rejected."},
            {"code": "E5-S2", "summary": "OTP fallback", "status": "Done",
             "context": "Numeric OTP for poor-signal hand-offs.",
             "ac": ["Hashed OTP issued; entry validates equivalently to QR"],
             "verify": "OTP path advances booking when QR unavailable."},
            {"code": "E5-S3", "summary": "Open-box inspection UI + event logging", "status": "Done",
             "context": "Traveller confirms contents before accepting; gate enforced server-side (E2-S8).",
             "ac": ["Checklist (versioned) completed before pickup scan", "OPEN_BOX_CONFIRMED audit + handoff_event written"],
             "verify": "Cannot scan pickup before completing the checklist."},
            {"code": "E5-S4", "summary": "Ratings -> trust score", "status": "Done",
             "context": "Post-delivery ratings update rating_avg and trust_score.",
             "ac": ["One review per booking per rater", "trust_score recomputed; surfaced on profile + ranking"],
             "verify": "Submitting a rating updates the ratee's score."},
        ],
    },
    # =====================================================================
    {
        "code": "E6",
        "summary": "Safety Net & Ops (Phase 4)",
        "status": "To Do",
        "context": "Embedded insurance, dispute resolution, the founder admin console, and compliance exports.",
        "ac": ["Insurance bound at checkout.", "Disputes resolvable with an evidence trail.",
               "Founder can run ops without DB access."],
        "children": [
            {"code": "E6-S1", "summary": "Embedded insurance (stub -> Anansi)", "status": "Done",
             "context": "Mandatory parcel cover at checkout; margin = premium charged - premium cost.",
             "ac": ["Policy bound per booking; INSURANCE_BOUND audit", "Stub first, real Anansi behind a flag"],
             "verify": "Checkout binds a policy and records the premium."},
            {"code": "E6-S2", "summary": "Dispute flow", "status": "Done",
             "context": "Open/resolve disputes (release/refund/split) backed by handoff + photo evidence.",
             "ac": ["Dispute lifecycle with admin resolution", "Resolution drives the Stripe refund path"],
             "verify": "A disputed booking can be resolved to release/refund/split."},
            {"code": "E6-S3", "summary": "Founder admin/ops console (Retool)", "status": "In Review",
             "context": "Disputes, payout overrides, reconciliation views for the founder.",
             "ac": ["Read/act on bookings, payments, disputes without direct DB access"],
             "verify": "Console performs a manual payout override end-to-end."},
            {"code": "E6-S4", "summary": "Compliance exports & reconciliation views", "status": "In Review",
             "context": "Operationalise the E2-S10 exports in the console.",
             "ac": ["One-click HMRC/Home Office/insurer exports for a date range"],
             "verify": "Exports render correct data for a seeded period."},
        ],
    },
    # =====================================================================
    {
        "code": "E7",
        "summary": "Client App (Expo iOS / Android / Web)",
        "status": "To Do",
        "context": "One Expo (React Native + react-native-web) codebase for iOS, Android, and web, using the "
                   "live Firebase phone auth and free maps (postcodes.io + MapLibre + OSM).",
        "ac": ["Phone-OTP auth works on web and native.",
               "Real addresses with map pins.",
               "Sender and traveller flows complete end-to-end."],
        "children": [
            {"code": "E7-S1", "summary": "Expo scaffold + Firebase phone auth", "status": "In Review",
             "context": "Expo Router app; phone-OTP via Firebase (JS SDK web, RN Firebase native).",
             "ac": ["App runs on iOS/Android/web", "Phone-OTP sign-in issues an ID token used by the API"],
             "verify": "Sign in with a test phone number on web + device."},
            {"code": "E7-S2", "summary": "AddressPicker (postcodes.io + MapLibre)", "status": "In Review",
             "context": "Postcode lookup -> confirm address -> pin on a free OSM map; web + native.",
             "ac": ["Invalid/non-GB postcode rejected", "Valid postcode resolves to a correct pin"],
             "verify": "Enter a UK postcode; pin renders on all platforms."},
            {"code": "E7-S3", "summary": "Sender flow screens", "status": "In Review",
             "context": "Post parcel, review bids, accept, fund escrow, show pickup QR, track, rate.",
             "ac": ["Full sender journey reachable", "Pricing shown as a contribution (framing-clean)"],
             "verify": "Walk the sender journey against the API."},
            {"code": "E7-S4", "summary": "Traveller flow screens", "status": "In Review",
             "context": "Post trip, browse matches (map), bid/claim, open-box, scan, see contribution.",
             "ac": ["Full traveller journey reachable", "Cap-exceeded bids surface the cost-sharing message"],
             "verify": "Walk the traveller journey against the API."},
            {"code": "E7-S5", "summary": "Live tracking via Firestore + FCM", "status": "In Review",
             "context": "Subscribe to booking_status; push on key transitions.",
             "ac": ["Status updates appear live", "Only participants can read the doc"],
             "verify": "Two devices see synchronized booking status."},
            {"code": "E7-S6", "summary": "Web build + Firebase Hosting (pbuddy.co.uk)", "status": "To Do",
             "context": "Deploy the Expo web build to Firebase Hosting on the custom domain.",
             "ac": ["Web app served at pbuddy.co.uk", "/api/** rewrites to Cloud Run"],
             "verify": "Core sender flow works in-browser at the domain."},
        ],
    },
    # =====================================================================
    {
        "code": "E8",
        "summary": "Pro Buddy Enablement (fast-follow)",
        "status": "To Do",
        "context": "Unlock the uncapped Pro Buddy tier safely: Right-to-Work verification, hire & reward "
                   "insurance for car drivers, and self-employed onboarding. Gated and audited. Students excluded.",
        "ac": ["Pro Buddy activates only with verified RTW (+ hire&reward for car).",
               "Students can never enter Pro Buddy.",
               "Every tier transition is audited."],
        "children": [
            {"code": "E8-S1", "summary": "Right-to-Work verification integration", "status": "To Do",
             "context": "Verify RTW before enabling uncapped earning.",
             "ac": ["RTW provider integrated; rtw_status flips to verified", "pro_requires_rtw constraint satisfied on upgrade"],
             "verify": "Upgrade blocked until RTW verified."},
            {"code": "E8-S2", "summary": "Hire & reward insurance (Zego) for car drivers", "status": "To Do",
             "context": "Car-driving Pros need hire & reward cover.",
             "ac": ["hire_reward_policy_id captured for car Pros", "proBypass blocked for car without it"],
             "verify": "Car Pro cannot bypass cap without a policy."},
            {"code": "E8-S3", "summary": "Self-employed onboarding + tax messaging", "status": "To Do",
             "context": "Pro is taxable self-employment — explicit acknowledgment + correct messaging (no trading-allowance framing).",
             "ac": ["self_employed_ack_at captured", "Pro receipts use earning/self-employment language, not cost-sharing"],
             "verify": "Pro onboarding records the acknowledgment."},
            {"code": "E8-S4", "summary": "Tier transition flow + audit", "status": "To Do",
             "context": "Casual -> Pro upgrade with all gates + TIER_TRANSITION audit.",
             "ac": ["Upgrade enforces all gates atomically", "TIER_TRANSITION written with evidence refs"],
             "verify": "Upgrade path audited; student upgrade impossible."},
        ],
    },
    # =====================================================================
    {
        "code": "E9",
        "summary": "GTM Pilot Enablement",
        "status": "To Do",
        "context": "Prove liquidity + unit economics on one corridor before cloning. Seed supply first, "
                   "manufacture concentrated demand, and instrument the metrics the next raise needs.",
        "ac": ["One corridor reaches healthy match rate.",
               "Demand never hits a dead end (courier backstop).",
               "Unit-economics metrics are measurable."],
        "children": [
            {"code": "E9-S1", "summary": "Corridor seeding (London-Manchester)", "status": "To Do",
             "context": "Recruit a roster of regular travellers + a sender waitlist on two campuses.",
             "ac": ["Seed traveller roster live", "Sender waitlist captured"],
             "verify": "First corridor has both supply and demand seeded."},
            {"code": "E9-S2", "summary": "Concierge liquidity + courier backstop", "status": "To Do",
             "context": "Manually match early bookings; cover with a backup courier if no traveller.",
             "ac": ["Concierge matching process documented + run", "Backstop covers unmatched demand"],
             "verify": "No early sender experiences a dead end."},
            {"code": "E9-S3", "summary": "Metrics dashboard (match rate, margin, CAC)", "status": "To Do",
             "context": "Instrument time-to-match, % matched, contribution margin/parcel, CAC vs LTV, compliance health.",
             "ac": ["Dashboard shows liquidity + unit-economics + zero-compliance-breach metrics"],
             "verify": "Dashboard reflects seeded pilot data."},
        ],
    },
]
