"""PBuddy work-breakdown structure: the backlog as data.

Edit this file and run ``python3 tools/jira_sync.py`` to push to Jira. Each item:
  code     stable WBS id (drives idempotent upsert via a code:<id> label)
  summary  issue title
  status   To Do | In Progress | In Review | Done
  context  why this exists
  ac       acceptance criteria — written to be testable
  verify   how to verify (command / manual step)
  refs     file paths / artefacts (for done or in-progress work)
"""

EPICS = [
    # =====================================================================
    {
        "code": "E1",
        "summary": "Foundations & Infrastructure (Phase 0)",
        "status": "In Progress",
        "context": "Stand up the monorepo, cloud project, and developer workflow so every "
                   "later phase is reproducible: one Expo codebase (iOS/Android/web), a "
                   "Cloud Run API, Postgres migrations, and GCP+Firebase wiring.",
        "ac": [
            "Monorepo builds and tests run from the repo root.",
            "GCP project pbuddy-mvp is connected with Firebase phone auth enabled.",
            "GitHub repo is synced with push/pull working.",
        ],
        "children": [
            {
                "code": "E1-S1", "summary": "Monorepo scaffold (api/app/db/infra)", "status": "Done",
                "context": "Workspace layout with api (Cloud Run), app (Expo), db (migrations), infra (GCP).",
                "ac": ["npm workspaces resolve", "api/app/db/infra directories exist",
                       "root scripts (api:test, db:migrate) defined"],
                "verify": "npm install at root succeeds; npm run api:test runs.",
                "refs": ["package.json", "README.md", ".gitignore"],
            },
            {
                "code": "E1-S2", "summary": "Postgres schema + forward-only migration runner", "status": "Done",
                "context": "Relational schema (money in pence) plus an idempotent migration runner.",
                "ac": ["0001_init.sql + 0002_seed.sql apply cleanly",
                       "migrate.mjs tracks applied files in schema_migrations",
                       "corridor allowlist + versioned legal_copy seeded"],
                "verify": "DATABASE_URL=... npm run db:migrate applies both migrations.",
                "refs": ["db/migrations/0001_init.sql", "db/migrations/0002_seed.sql", "db/migrate.mjs"],
            },
            {
                "code": "E1-S3", "summary": "GCP + Firebase wiring (pbuddy-mvp)", "status": "Done",
                "context": "Connect the repo to the live GCP/Firebase project, enable phone auth, lock Firestore.",
                "ac": ["Project pbuddy-mvp active; required APIs enabled",
                       "Firebase phone sign-in enabled",
                       "Firestore security rules deployed (read-only status mirror, server-only writes)",
                       "Web SDK config wired into the client"],
                "verify": "Admin config shows signIn.phoneNumber.enabled=true; firebase deploy --only firestore:rules succeeds.",
                "refs": [".firebaserc", "firebase.json", "firestore.rules", "app/firebaseConfig.ts"],
            },
            {
                "code": "E1-S4", "summary": "GitHub repo + credential sync", "status": "Done",
                "context": "Initialise git, connect origin, keep push/pull synced without leaking the PAT.",
                "ac": ["origin = github.com/khanwaseemraza/pbuddy with clean URL (no token)",
                       "credentials stored outside the repo; .env and secrets gitignored",
                       "main pushed and tracking origin/main"],
                "verify": "git push / git fetch work; git status clean; no secrets in tracked files.",
                "refs": ["~/.pbuddy-git-credentials (outside repo)"],
            },
            {
                "code": "E1-S5", "summary": "CI pipeline (tests + framing lint + typecheck)", "status": "Done",
                "context": "GitHub Actions running unit tests, the framing banned-word lint, and tsc on every PR.",
                "ac": ["Workflow runs npm test, lint:framing, typecheck on push/PR",
                       "DB-gated integration tests run against an ephemeral Postgres service",
                       "Red build blocks merge"],
                "verify": "Open a PR; checks appear and pass/fail correctly.",
            },
            {
                "code": "E1-S6", "summary": "Cloud Run + Cloud SQL provisioning (deferred)", "status": "Done",
                "context": "Provision Cloud SQL (Postgres) and deploy the API to Cloud Run via Cloud Build. "
                           "Deferred per cost decision; everything is pre-wired.",
                "ac": ["Cloud SQL instance + DB created; migrations applied",
                       "API deployed to Cloud Run with Cloud SQL connector + secrets",
                       "Region co-located with Firestore (europe-west2) decision recorded"],
                "verify": "gcloud builds submit --config infra/cloudbuild.yaml deploys; /readyz returns ready.",
                "refs": ["infra/Dockerfile", "infra/cloudbuild.yaml"],
            },
        ],
    },
    # =====================================================================
    {
        "code": "E2",
        "summary": "Compliance & Cost-Sharing Firewall (legal-as-code)",
        "status": "In Progress",
        "context": "PBuddy's legal survival depends on staying a cost-sharing / expense-reimbursement "
                   "platform, never hire & reward. These rules are enforced as DB-level invariants and "
                   "server-side checks, with an immutable audit trail — not buried in T&Cs.",
        "ac": [
            "A traveller can never accept contributions exceeding their own journey cost.",
            "A student-visa user can never become Pro Buddy.",
            "Every legally-relevant decision is recorded in an append-only audit log.",
        ],
        "children": [
            {
                "code": "E2-S1", "summary": "Capacity ledger with committed<=cap invariant", "status": "Done",
                "context": "Per-trip ledger; the cost-sharing invariant is a DB CHECK constraint.",
                "ac": ["trip_capacity_ledger created per trip with cap = locked journey cost",
                       "CHECK (committed_pennies <= cap_pennies) rejects over-commit",
                       "remaining_pennies is a generated column (cannot drift)"],
                "verify": "Integration test: direct UPDATE over cap is rejected by the constraint.",
                "refs": ["db/migrations/0001_init.sql", "api/test/firewall.integration.test.ts"],
            },
            {
                "code": "E2-S2", "summary": "evaluateCap + atomic reserveCapacity (concurrency-safe)", "status": "Done",
                "context": "Pure cap decision + row-locked reservation so concurrent accepts serialize.",
                "ac": ["evaluateCap rejects contributions that breach the cap (incl. cumulative)",
                       "reserveCapacity locks the ledger row (FOR UPDATE) before committing",
                       "Concurrent accepts on one trip can never exceed the cap"],
                "verify": "npm run api:test (unit) + concurrent-accept integration test asserts exactly one succeeds.",
                "refs": ["api/src/services/caps.ts", "api/test/caps.test.ts", "api/src/db.ts"],
            },
            {
                "code": "E2-S3", "summary": "Cap-bounded bidding enforcement (place + accept)", "status": "Done",
                "context": "Bids are validated against the cap at creation and re-validated atomically at accept.",
                "ac": ["A bid above sender max or above remaining cap is rejected",
                       "Accept reserves capacity atomically and creates the booking",
                       "Competing bids on the parcel expire on accept"],
                "verify": "Place a bid over cap -> 409 cap_exceeded; accept under cap -> 201 booking.",
                "refs": ["api/src/routes/bids.ts"],
            },
            {
                "code": "E2-S4", "summary": "Trip-frequency throttle (incidental-traveller bounds)", "status": "Done",
                "context": "Cap trips/week (global + per route) so Casual users look like travellers, not couriers; "
                           "hitting the ceiling flags a Pro Buddy upgrade signal.",
                "ac": ["evaluateFrequency blocks at weekly/route/monthly ceilings",
                       "Blocked publish returns an upgrade signal for eligible non-students",
                       "Counters persisted in user_trip_counters and enforced at trip publish"],
                "verify": "Unit tests pass; publishing past the weekly limit is blocked (route handler TBD).",
                "refs": ["api/src/services/frequency.ts", "api/test/caps.test.ts"],
            },
            {
                "code": "E2-S5", "summary": "Two-tier model: Casual/Pro DB constraints", "status": "Done",
                "context": "Casual Buddy = safe harbour; Pro Buddy = uncapped but gated by RTW + hire&reward.",
                "ac": ["CHECK students_cannot_be_pro blocks student_visa + pro_buddy",
                       "CHECK pro_requires_rtw blocks pro_buddy without verified RTW",
                       "proBypassAllowed() bypasses the cap only when gates are satisfied"],
                "verify": "Integration test: inserting a student-visa Pro user is rejected; proBypass unit tests pass.",
                "refs": ["db/migrations/0001_init.sql", "api/src/services/caps.ts"],
            },
            {
                "code": "E2-S6", "summary": "Append-only hash-chained compliance audit log", "status": "Done",
                "context": "Tamper-evident evidence trail for HMRC / Home Office / insurers.",
                "ac": ["Each row hash-chains to the previous (prev_hash/row_hash)",
                       "UPDATE/DELETE are forbidden by trigger",
                       "writeAudit() records CAP_CHECK etc. inside the same transaction"],
                "verify": "Integration test: UPDATE on compliance_audit_log raises 'append-only'.",
                "refs": ["db/migrations/0001_init.sql", "api/src/lib/audit.ts"],
            },
            {
                "code": "E2-S7", "summary": "Framing lint + versioned legal copy", "status": "Done",
                "context": "Never call a contribution a 'fee'/'earnings' on the user-facing path.",
                "ac": ["banned-words lint fails CI on banned terms in user-facing strings",
                       "Internal revenue terms (platform_fee/escrow_fee) are allowlisted",
                       "legal_copy table holds versioned framing strings"],
                "verify": "node api/scripts/banned-words.mjs prints 'framing lint clean'.",
                "refs": ["api/scripts/banned-words.mjs", "db/migrations/0002_seed.sql"],
            },
            {
                "code": "E2-S8", "summary": "Open-box gate (pickup blocked without inspection)", "status": "Done",
                "context": "Traveller must inspect unsealed contents before escrow arms.",
                "ac": ["A booking cannot reach picked_up without an open_box_confirmed event",
                       "Enforced by DB trigger as the structural backstop"],
                "verify": "Attempt to set status=picked_up with no open-box event -> exception.",
                "refs": ["db/migrations/0001_init.sql"],
            },
            {
                "code": "E2-S9", "summary": "Domestic-only allowlist + GB postcode validation", "status": "Done",
                "context": "Corridors are a curated UK allowlist; pickup/dropoff postcodes validated GB via postcodes.io.",
                "ac": ["No international route can be created (none exist in the table)",
                       "Both pickup and dropoff resolve to valid GB postcodes",
                       "ROUTE_VALIDATED audit event written"],
                "verify": "Posting a non-GB postcode is rejected; valid postcode resolves to lat/lng.",
            },
            {
                "code": "E2-S11", "summary": "User provisioning + real Firebase token verification", "status": "Done",
                "context": "The auth middleware verifies a Firebase ID token but requires the users row to "
                           "already exist (403 user_not_provisioned). Add token verification without a service "
                           "account (verifyIdToken needs only the project id) and a POST /users/me that "
                           "auto-creates the user from the verified token, so the app can make authenticated calls.",
                "ac": ["API verifies real Firebase ID tokens (no ADC/service-account needed; project id only)",
                       "POST /users/me upserts the user from the verified token (uid + phone)",
                       "Authenticated endpoints work after first provisioning; dev-bypass still works for tests"],
                "verify": "Sign in on web -> app provisions the user -> /corridors loads. Integration test covers upsert.",
                "refs": ["api/src/middleware/auth.ts", "api/src/lib/firebase.ts", "api/src/routes/users.ts"],
            },
            {
                "code": "E2-S10", "summary": "Compliance evidence exports (HMRC/Home Office/insurer)", "status": "Done",
                "context": "First-class reports from the audit log proving the rules were enforced.",
                "ac": ["Per-user annual gross contribution + cap-enforcement export (HMRC)",
                       "Per-student Tier-1 lock + reimbursement-only export (Home Office)",
                       "Route/mode/open-box/prohibited-items export (insurer)"],
                "verify": "Export endpoints return correct aggregates for seeded data.",
            },
        ],
    },
    # =====================================================================
    {
        "code": "E3",
        "summary": "Marketplace Core: Matching & Bidding (Phase 1)",
        "status": "In Progress",
        "context": "The two-sided marketplace: post trips/parcels, match them, and run cap-bounded "
                   "price discovery (reverse auction) that can never breach the cost-sharing invariant.",
        "ac": [
            "Senders post parcels with real addresses; travellers post trips.",
            "Matching surfaces only cap-valid, in-corridor, fitting candidates.",
            "Bidding produces a booking without breaching the cap.",
        ],
        "children": [
            {
                "code": "E3-S1", "summary": "Trips: create with locked journey cost + ledger init", "status": "Done",
                "context": "Journey cost is captured and locked at creation; the ledger is auto-created by trigger.",
                "ac": ["Trip stores journey_cost + source + cost_locked_at",
                       "trip_capacity_ledger row auto-created with cap = journey cost"],
                "verify": "Integration test: ledger auto-created with cap = journey cost.",
                "refs": ["db/migrations/0001_init.sql"],
            },
            {
                "code": "E3-S2", "summary": "Parcels: post with real addresses + value/dimension caps", "status": "Done",
                "context": "Sender posts a parcel with GB pickup/dropoff addresses, size/value within caps, pricing mode.",
                "ac": ["declared_value <= configured cap; dimensions <= 100cm; piece_count 1..3",
                       "pickup/dropoff postcode+address+lat/lng stored",
                       "pricing_mode fixed/auction with suggested/max contribution"],
                "verify": "POST parcel persists addresses; over-cap value/dimension rejected (schema done; route TBD).",
                "refs": ["db/migrations/0001_init.sql"],
            },
            {
                "code": "E3-S3", "summary": "Matching engine: candidates + proximity/trust ranking", "status": "Done",
                "context": "SQL hard filters + Haversine proximity + trust scoring (no ML for MVP).",
                "ac": ["Filters: same corridor+direction, KYC-verified, window overlap, cap-affordable, fits luggage",
                       "Ranking prefers higher contribution + closer detour + more trusted sender"],
                "verify": "Unit test rankForTraveler orders near-rich above far-cheap; GET /trips/:id/matches.",
                "refs": ["api/src/services/matching.ts", "api/src/routes/matching.ts", "api/test/caps.test.ts"],
            },
            {
                "code": "E3-S4", "summary": "Bids API: place + accept (booking creation)", "status": "Done",
                "context": "Travellers bid; senders accept; booking created atomically with cap reservation.",
                "ac": ["POST /parcels/:id/bids validates cap + sender max + luggage",
                       "POST /bids/:id/accept creates booking, expires competing bids, marks parcel matched"],
                "verify": "Manual: place + accept flow returns booking_id; competing bids expire.",
                "refs": ["api/src/routes/bids.ts"],
            },
            {
                "code": "E3-S5", "summary": "Price suggestion (cold-start helper)", "status": "Done",
                "context": "Size-band x distance-band suggested contribution, clamped to the cap, to anchor senders.",
                "ac": ["Suggested contribution computed from bands and never exceeds the cap",
                       "Surfaced on the post-parcel form"],
                "verify": "Suggestion endpoint returns a sane, capped value for given size/distance.",
            },
            {
                "code": "E3-S6", "summary": "Booking lifecycle + Firestore status mirror", "status": "Done",
                "context": "Drive booking states and mirror status to Firestore for live client updates.",
                "ac": ["Lifecycle transitions enforced server-side",
                       "Each transition writes a booking_status doc readable only by participants",
                       "FCM push on key transitions"],
                "verify": "Client subscribed to booking_status sees updates; non-participants are denied.",
            },
        ],
    },
    # =====================================================================
    {
        "code": "E4",
        "summary": "Payments & Identity: Escrow + KYC (Phase 2)",
        "status": "To Do",
        "context": "Stripe Connect escrow via manual capture + Stripe Identity KYC. The riskiest block — "
                   "money moves only server-side in response to signed webhooks.",
        "ac": ["Funds authorized at funding, captured at pickup, transferred at dropoff.",
               "Both sides KYC-verified before transacting.",
               "Refunds and reconciliation work end-to-end in Stripe test mode."],
        "children": [
            {"code": "E4-S1", "summary": "Stripe Connect Express onboarding (travellers)", "status": "Done",
             "context": "Travellers onboard as payees; Stripe runs payee KYC/AML.",
             "ac": ["Connect Express account created + linked to user", "Payout-ready status tracked"],
             "verify": "Onboarding link completes; stripe_connect_id stored."},
            {"code": "E4-S2", "summary": "Stripe Identity KYC (both sides)", "status": "Done",
             "context": "Verify sender + traveller identity before they can transact.",
             "ac": ["KYC session created; webhook flips users.kyc_status", "Posting/claiming blocked until verified"],
             "verify": "Test-mode verification flips kyc_status to verified."},
            {"code": "E4-S3", "summary": "Manual-capture funding (authorize)", "status": "Done",
             "context": "Sender funds escrow: authorize full amount (capture_method=manual).",
             "ac": ["PaymentIntent authorized; payment row state=authorized", "Itemized: contribution + £1.50 + insurance"],
             "verify": "Funding authorizes a test card; ledger row created."},
            {"code": "E4-S4", "summary": "Capture on pickup, transfer on dropoff", "status": "Done",
             "context": "Capture funds on pickup scan; transfer payout to traveller on dropoff scan.",
             "ac": ["Pickup scan captures the intent (state=captured)", "Dropoff scan transfers payout (state=released)"],
             "verify": "Test-mode end-to-end: authorize -> capture -> transfer."},
            {"code": "E4-S5", "summary": "Refunds & partial refunds", "status": "Done",
             "context": "Cancel uncaptured / refund captured / admin split on dispute.",
             "ac": ["Uncaptured cancel releases hold", "Captured refund + partial split supported"],
             "verify": "Dispute paths produce correct Stripe refunds."},
            {"code": "E4-S6", "summary": "Reconciliation: ledger vs Stripe", "status": "Done",
             "context": "Reconcile internal payment ledger against Stripe balance/transactions.",
             "ac": ["Daily reconciliation report flags mismatches"],
             "verify": "Seeded transactions reconcile cleanly."},
        ],
    },
    # =====================================================================
    {
        "code": "E5",
        "summary": "Hand-off & Trust (Phase 3)",
        "status": "To Do",
        "context": "Secure QR/OTP hand-off at pickup and dropoff, the open-box inspection step, and ratings "
                   "feeding a trust score.",
        "ac": ["Pickup/dropoff confirmed by QR (OTP fallback).",
               "Open-box inspection required before pickup.",
               "Ratings update a visible trust score."],
        "children": [
            {"code": "E5-S1", "summary": "QR token generation + scanner", "status": "Done",
             "context": "Single-use QR tokens shown by one party, scanned by the other.",
             "ac": ["Pickup/dropoff QR tokens generated per booking", "Scan validates token + logs handoff_event"],
             "verify": "Scanning a valid token advances the booking; reused token rejected."},
            {"code": "E5-S2", "summary": "OTP fallback", "status": "Done",
             "context": "Numeric OTP for poor-signal hand-offs.",
             "ac": ["Hashed OTP issued; entry validates equivalently to QR"],
             "verify": "OTP path advances booking when QR unavailable."},
            {"code": "E5-S3", "summary": "Open-box inspection UI + event logging", "status": "Done",
             "context": "Traveller confirms contents before accepting; gate enforced server-side (E2-S8).",
             "ac": ["Checklist (versioned) completed before pickup scan", "OPEN_BOX_CONFIRMED audit + handoff_event written"],
             "verify": "Cannot scan pickup before completing the checklist."},
            {"code": "E5-S4", "summary": "Ratings -> trust score", "status": "Done",
             "context": "Post-delivery ratings update rating_avg and trust_score.",
             "ac": ["One review per booking per rater", "trust_score recomputed; surfaced on profile + ranking"],
             "verify": "Submitting a rating updates the ratee's score."},
        ],
    },
    # =====================================================================
    {
        "code": "E6",
        "summary": "Safety Net & Ops (Phase 4)",
        "status": "To Do",
        "context": "Embedded insurance, dispute resolution, the founder admin console, and compliance exports.",
        "ac": ["Insurance bound at checkout.", "Disputes resolvable with an evidence trail.",
               "Founder can run ops without DB access."],
        "children": [
            {"code": "E6-S1", "summary": "Embedded insurance (stub -> Anansi)", "status": "Done",
             "context": "Mandatory parcel cover at checkout; margin = premium charged - premium cost.",
             "ac": ["Policy bound per booking; INSURANCE_BOUND audit", "Stub first, real Anansi behind a flag"],
             "verify": "Checkout binds a policy and records the premium."},
            {"code": "E6-S2", "summary": "Dispute flow", "status": "Done",
             "context": "Open/resolve disputes (release/refund/split) backed by handoff + photo evidence.",
             "ac": ["Dispute lifecycle with admin resolution", "Resolution drives the Stripe refund path"],
             "verify": "A disputed booking can be resolved to release/refund/split."},
            {"code": "E6-S3", "summary": "Founder admin/ops console (Retool)", "status": "In Review",
             "context": "Disputes, payout overrides, reconciliation views for the founder.",
             "ac": ["Read/act on bookings, payments, disputes without direct DB access"],
             "verify": "Console performs a manual payout override end-to-end."},
            {"code": "E6-S4", "summary": "Compliance exports & reconciliation views", "status": "In Review",
             "context": "Operationalise the E2-S10 exports in the console.",
             "ac": ["One-click HMRC/Home Office/insurer exports for a date range"],
             "verify": "Exports render correct data for a seeded period."},
        ],
    },
    # =====================================================================
    {
        "code": "E7",
        "summary": "Client App (Expo iOS / Android / Web)",
        "status": "To Do",
        "context": "One Expo (React Native + react-native-web) codebase for iOS, Android, and web, using the "
                   "live Firebase phone auth and free maps (postcodes.io + MapLibre + OSM).",
        "ac": ["Phone-OTP auth works on web and native.",
               "Real addresses with map pins.",
               "Sender and traveller flows complete end-to-end."],
        "children": [
            {"code": "E7-S1", "summary": "Expo scaffold + Firebase phone auth", "status": "Done",
             "context": "Expo Router app; phone-OTP via Firebase (JS SDK web, RN Firebase native).",
             "ac": ["App runs on iOS/Android/web", "Phone-OTP sign-in issues an ID token used by the API"],
             "verify": "Sign in with a test phone number on web + device."},
            {"code": "E7-S2", "summary": "AddressPicker (postcodes.io + MapLibre)", "status": "In Review",
             "context": "Postcode lookup -> confirm address -> pin on a free OSM map; web + native.",
             "ac": ["Invalid/non-GB postcode rejected", "Valid postcode resolves to a correct pin"],
             "verify": "Enter a UK postcode; pin renders on all platforms."},
            {"code": "E7-S3", "summary": "Sender flow screens", "status": "In Review",
             "context": "Post parcel, review bids, accept, fund escrow, show pickup QR, track, rate.",
             "ac": ["Full sender journey reachable", "Pricing shown as a contribution (framing-clean)"],
             "verify": "Walk the sender journey against the API."},
            {"code": "E7-S4", "summary": "Traveller flow screens", "status": "In Review",
             "context": "Post trip, browse matches (map), bid/claim, open-box, scan, see contribution.",
             "ac": ["Full traveller journey reachable", "Cap-exceeded bids surface the cost-sharing message"],
             "verify": "Walk the traveller journey against the API."},
            {"code": "E7-S5", "summary": "Live tracking via Firestore + FCM", "status": "In Review",
             "context": "Subscribe to booking_status; push on key transitions.",
             "ac": ["Status updates appear live", "Only participants can read the doc"],
             "verify": "Two devices see synchronized booking status."},
            {"code": "E7-S6", "summary": "Web build + Firebase Hosting (pbuddy.co.uk)", "status": "Done",
             "context": "Deploy the Expo web build to Firebase Hosting on the custom domain.",
             "ac": ["Web app served at pbuddy.co.uk", "/api/** rewrites to Cloud Run"],
             "verify": "Core sender flow works in-browser at the domain."},
        ],
    },
    # =====================================================================
    {
        "code": "E8",
        "summary": "Pro Buddy Enablement (fast-follow)",
        "status": "To Do",
        "context": "Unlock the uncapped Pro Buddy tier safely: Right-to-Work verification, hire & reward "
                   "insurance for car drivers, and self-employed onboarding. Gated and audited. Students excluded.",
        "ac": ["Pro Buddy activates only with verified RTW (+ hire&reward for car).",
               "Students can never enter Pro Buddy.",
               "Every tier transition is audited."],
        "children": [
            {"code": "E8-S1", "summary": "Right-to-Work verification integration", "status": "Done",
             "context": "Verify RTW before enabling uncapped earning.",
             "ac": ["RTW provider integrated; rtw_status flips to verified", "pro_requires_rtw constraint satisfied on upgrade"],
             "verify": "Upgrade blocked until RTW verified."},
            {"code": "E8-S2", "summary": "Hire & reward insurance (Zego) for car drivers", "status": "Done",
             "context": "Car-driving Pros need hire & reward cover.",
             "ac": ["hire_reward_policy_id captured for car Pros", "proBypass blocked for car without it"],
             "verify": "Car Pro cannot bypass cap without a policy."},
            {"code": "E8-S3", "summary": "Self-employed onboarding + tax messaging", "status": "Done",
             "context": "Pro is taxable self-employment — explicit acknowledgment + correct messaging (no trading-allowance framing).",
             "ac": ["self_employed_ack_at captured", "Pro receipts use earning/self-employment language, not cost-sharing"],
             "verify": "Pro onboarding records the acknowledgment."},
            {"code": "E8-S4", "summary": "Tier transition flow + audit", "status": "Done",
             "context": "Casual -> Pro upgrade with all gates + TIER_TRANSITION audit.",
             "ac": ["Upgrade enforces all gates atomically", "TIER_TRANSITION written with evidence refs"],
             "verify": "Upgrade path audited; student upgrade impossible."},
        ],
    },
    # =====================================================================
    {
        "code": "E9",
        "summary": "GTM Pilot Enablement",
        "status": "To Do",
        "context": "Prove liquidity + unit economics on one corridor before cloning. Seed supply first, "
                   "manufacture concentrated demand, and instrument the metrics the next raise needs.",
        "ac": ["One corridor reaches healthy match rate.",
               "Demand never hits a dead end (courier backstop).",
               "Unit-economics metrics are measurable."],
        "children": [
            {"code": "E9-S1", "summary": "Corridor seeding (London-Manchester)", "status": "In Progress",
             "context": "Recruit a roster of regular travellers + a sender waitlist on two campuses.",
             "ac": ["Seed traveller roster live", "Sender waitlist captured"],
             "verify": "First corridor has both supply and demand seeded."},
            {"code": "E9-S2", "summary": "Concierge liquidity + courier backstop", "status": "In Progress",
             "context": "Manually match early bookings; cover with a backup courier if no traveller.",
             "ac": ["Concierge matching process documented + run", "Backstop covers unmatched demand"],
             "verify": "No early sender experiences a dead end."},
            {"code": "E9-S3", "summary": "Metrics dashboard (match rate, margin, CAC)", "status": "Done",
             "context": "Instrument time-to-match, % matched, contribution margin/parcel, CAC vs LTV, compliance health.",
             "ac": ["Dashboard shows liquidity + unit-economics + zero-compliance-breach metrics"],
             "verify": "Dashboard reflects seeded pilot data."},
        ],
    },
    # =====================================================================
    {
        "code": "E10",
        "summary": "Production Hardening & Launch Readiness",
        "status": "To Do",
        "context": "The MVP is built and live end-to-end on pbuddy.co.uk (real OTP -> provisioning -> "
                   "Cloud Run API -> Cloud SQL). Before opening to the public with real money, harden the "
                   "security, reliability, and legal surface. This epic is the gate between a working demo "
                   "and a public pilot: bot/toll-fraud protection, abuse limits, signed money-moving "
                   "webhooks, secret rotation, observability, backups/DR, and the live legal pages.",
        "ac": [
            "Phone auth and money-moving endpoints are protected against bots, abuse, and replay.",
            "Operators get alerted on failures; the database can be restored to a point in time.",
            "Required legal pages are live and consent is captured at sign-up.",
        ],
        "children": [
            {"code": "E10-S1", "summary": "reCAPTCHA Enterprise ENFORCE + Firebase App Check", "status": "To Do",
             "context": "Phone auth currently runs reCAPTCHA in AUDIT (non-blocking). Flip to ENFORCE and add "
                        "Firebase App Check (reCAPTCHA Enterprise on web, Play Integrity on Android, App Attest/"
                        "DeviceCheck on iOS) so only genuine app instances can call Identity Platform and the API.",
             "ac": ["phoneEnforcementState = ENFORCE on the Identity Platform recaptchaConfig",
                    "App Check enforced on Firebase Auth (and optionally proxied to the API)",
                    "A request with no/invalid attestation token is rejected"],
             "verify": "Sign-in from a non-attested client is blocked; a real device/browser still signs in.",
             "refs": ["recaptcha key 6Lfy... (project pbuddy-mvp)"]},
            {"code": "E10-S2", "summary": "API rate limiting + Cloud Armor abuse protection", "status": "Done",
             "context": "No throttling exists today. Add per-IP and per-uid rate limits on auth-adjacent and all "
                        "write endpoints, plus an edge WAF in front of Cloud Run.",
             "ac": ["@fastify/rate-limit (or equivalent) caps write/bid/payment endpoints per uid + per IP",
                    "Cloud Armor policy fronts the Cloud Run service (or the LB) with sane defaults",
                    "Exceeding the limit returns 429 with Retry-After; limits are configurable"],
             "verify": "A burst of requests past the limit returns 429; normal usage is unaffected."},
            {"code": "E10-S3", "summary": "Stripe webhook signature verification + idempotency (prod)", "status": "Done",
             "context": "Money moves only in response to webhooks. Harden the prod path: verify the Stripe-Signature "
                        "header with the endpoint secret, enforce idempotency, and reject replays.",
             "ac": ["Every webhook verifies Stripe-Signature against STRIPE_WEBHOOK_SECRET (raw body)",
                    "Duplicate/replayed events are no-ops (idempotency on event id)",
                    "Unverified or stale-timestamp events are rejected and logged"],
             "verify": "stripe trigger / replayed event: valid is processed once, tampered is rejected.",
             "refs": ["api/src/routes/payments.ts", "api/src/lib/stripe.ts"]},
            {"code": "E10-S4", "summary": "Secret rotation + least-privilege IAM audit", "status": "To Do",
             "context": "The GitHub PAT, Jira token, and Stripe test key were shared in plaintext during setup and "
                        "should be rotated. Audit the runtime service account for least privilege.",
             "ac": ["GitHub PAT, Jira token rotated; Stripe key rotated before live mode",
                    "Secrets remain in Secret Manager / ~/.pbuddy-secrets.env (never in the repo)",
                    "pbuddy-run@ SA scoped to only Cloud SQL client + Firestore + required secrets"],
             "verify": "Old credentials no longer authenticate; deploy + app still work with rotated secrets."},
            {"code": "E10-S5", "summary": "Observability: structured logs, error tracking, uptime + alerts", "status": "Done",
             "context": "Add structured request logging, error reporting, an uptime check, and alert policies so "
                        "failures page someone instead of being discovered by users.",
             "ac": ["JSON structured logs with request id + uid (no PII/secrets) in Cloud Logging",
                    "Error Reporting captures unhandled exceptions",
                    "Uptime check on /readyz + alert policies (5xx rate, DB CPU/connections, payment failures)"],
             "verify": "Forcing a 5xx fires an alert; uptime check shows green on /readyz.",
             "refs": ["api/src/server.ts"]},
            {"code": "E10-S6", "summary": "Cloud SQL automated backups, PITR + DR runbook", "status": "Done",
             "context": "Production data needs recoverability. Enable automated backups and point-in-time recovery, "
                        "test a restore, and document the runbook.",
             "ac": ["Automated daily backups + PITR (WAL) enabled on pbuddy-db",
                    "A restore to a new instance is tested and verified",
                    "DR runbook (RPO/RTO, restore steps) documented in infra/"],
             "verify": "Restore the latest backup to a scratch instance; migrations + a smoke query pass.",
             "refs": ["infra/cloudsql.sh"]},
            {"code": "E10-S7", "summary": "Legal pages live + consent capture", "status": "Done",
             "context": "Surface the versioned legal copy as real pages and capture consent at sign-up: Terms, "
                        "Privacy, Prohibited Items, and the cost-sharing explainer (framing-clean).",
             "ac": ["T&Cs, Privacy, Prohibited Items, cost-sharing explainer reachable from the app/site",
                    "Sign-up records accepted legal_copy version + timestamp",
                    "Pages pass the framing lint (no fee/earnings on cost-sharing path)"],
             "verify": "Sign-up writes the consent record; pages render on web; framing lint clean.",
             "refs": ["db/migrations/0002_seed.sql (legal_copy)", "api/scripts/banned-words.mjs"]},
            {"code": "E10-S8", "summary": "Load & resilience test at pilot scale + SLOs", "status": "Done",
             "context": "Validate the system holds up at pilot concurrency and define the SLOs we alert on.",
             "ac": ["k6/artillery scenario covers sign-in, post, bid/accept, escrow at pilot concurrency",
                    "p95 latency + error budget SLOs defined and met against a staging deploy",
                    "Cloud Run min-instances / concurrency / Cloud SQL tier sized from the results"],
             "verify": "Load run meets the SLOs with no cap-constraint or DB errors."},
        ],
    },
    # =====================================================================
    {
        "code": "E11",
        "summary": "Native Mobile Apps (iOS / Android)",
        "status": "To Do",
        "context": "Web works today; native phone auth and push were deferred to an EAS dev build (PBD-44). "
                   "Ship installable iOS and Android apps so travellers/senders get native OTP, push "
                   "notifications, and store distribution — the main acquisition channel for a logistics app.",
        "ac": [
            "Native phone-OTP sign-in works on real iOS and Android devices.",
            "Push notifications fire on key booking transitions.",
            "Apps are accepted into TestFlight and Play closed testing.",
        ],
        "children": [
            {"code": "E11-S1", "summary": "EAS dev build + @react-native-firebase native phone auth", "status": "Done",
             "context": "Add the native Firebase config plugin and EAS build profiles; wire native phone-OTP via "
                        "@react-native-firebase/auth (the JS SDK path is web-only).",
             "ac": ["eas.json profiles (dev/preview/prod); GoogleService-Info.plist + google-services.json wired",
                    "Native OTP issues an ID token the API accepts (same verifyIdToken path)",
                    "AUTH works on a physical iOS and Android device"],
             "verify": "Install the dev build on a device; sign in with a real number; /corridors loads.",
             "refs": ["app/app.json", "app/src/lib/firebase.ts"]},
            {"code": "E11-S2", "summary": "Push notifications (FCM Android + APNs iOS)", "status": "In Review",
             "context": "Deliver push on key booking transitions (bid received, accepted, picked up, delivered), "
                        "completing the deferred part of the live-tracking story (E7-S5).",
             "ac": ["Device FCM/APNs token registered against the user server-side",
                    "Booking lifecycle transitions enqueue a push to the right participant",
                    "Tapping a notification deep-links to the booking"],
             "verify": "A status change on one device pushes a notification to the counterparty device.",
             "refs": ["api/src/lib/mirror.ts", "api/src/services/bookingLifecycle.ts"]},
            {"code": "E11-S3", "summary": "Native AddressPicker + maps parity", "status": "In Review",
             "context": "Ensure postcode lookup + map pin (MapLibre/OSM) render correctly on native, matching web.",
             "ac": ["AddressPicker validates GB postcodes and drops a correct pin on iOS + Android",
                    "Location permission flow handled gracefully"],
             "verify": "Enter a UK postcode on each native platform; the pin renders at the right place.",
             "refs": ["app/src/components/AddressPicker.tsx", "app/src/components/MapPin.tsx"]},
            {"code": "E11-S4", "summary": "Store assets, metadata + data-safety disclosures", "status": "To Do",
             "context": "Produce icons, screenshots, descriptions, and the privacy disclosures both stores require.",
             "ac": ["App icons + splash + store screenshots for both platforms",
                    "Apple privacy nutrition labels + Google Play Data Safety form completed",
                    "Store listings (name, description, keywords, support URL) drafted"],
             "verify": "Listings pass each store's pre-submission validation."},
            {"code": "E11-S5", "summary": "TestFlight + Play internal testing (closed beta)", "status": "To Do",
             "context": "Distribute to pilot users via TestFlight and Play internal testing before public release.",
             "ac": ["Build uploaded to TestFlight; internal testers can install",
                    "Build on Play internal testing track; testers can install",
                    "Crash/feedback channel wired"],
             "verify": "A pilot tester installs from each track and completes a booking."},
            {"code": "E11-S6", "summary": "Store submission & review (App Store + Play)", "status": "To Do",
             "context": "Submit for review and address any rejections; go live on both stores.",
             "ac": ["App Store + Play submissions pass review", "Public listings live; phased rollout configured"],
             "verify": "Both apps are downloadable from the public stores."},
        ],
    },
    # =====================================================================
    {
        "code": "E12",
        "summary": "Growth, Referrals & Retention (post-pilot)",
        "status": "To Do",
        "context": "Once the pilot (E9) proves liquidity and unit economics, drive acquisition and repeat usage: "
                   "a two-sided referral loop, lifecycle notifications, corridor SEO, and repeat-booking nudges. "
                   "Sequenced AFTER pilot validation so we amplify a working loop, not a leaky one.",
        "ac": [
            "Referrals are attributed, two-sided, and fraud-guarded.",
            "Lapsed users get re-engaged through lifecycle messaging.",
            "Repeat bookings are made frictionless (saved routes / one-tap repost).",
        ],
        "children": [
            {"code": "E12-S1", "summary": "Two-sided referral program (attributed + fraud-guarded)", "status": "To Do",
             "context": "Referral codes/links that reward both referrer and referee on a qualifying first booking, "
                        "with self-referral and abuse guards. Rewards framed compliantly (account credit, not 'earnings').",
             "ac": ["Unique referral code/link per user; attribution captured at sign-up",
                    "Reward granted only on a qualifying first completed booking",
                    "Self-referral / duplicate-device / velocity abuse blocked"],
             "verify": "A referred sign-up that completes a booking credits both parties exactly once."},
            {"code": "E12-S2", "summary": "Lifecycle notifications + re-engagement", "status": "To Do",
             "context": "Triggered messaging (push/email) for ratings prompts, abandoned posts, and lapsed users.",
             "ac": ["Post-delivery rating prompt; abandoned-parcel reminder; win-back for lapsed users",
                    "Quiet hours + per-user frequency caps + unsubscribe respected"],
             "verify": "Each trigger fires once under the right condition and respects opt-out."},
            {"code": "E12-S3", "summary": "Per-corridor SEO landing pages", "status": "To Do",
             "context": "Indexable landing pages per active corridor (e.g. London->Manchester parcel sending) to "
                        "capture organic demand, framing-clean.",
             "ac": ["A generated page per active corridor with correct metadata + structured data",
                    "Pages are crawlable/indexable and pass the framing lint"],
             "verify": "Corridor pages render with correct content + metadata and are indexable."},
            {"code": "E12-S4", "summary": "Saved routes + one-tap repeat booking", "status": "To Do",
             "context": "Reduce friction for repeat senders/travellers: save frequent routes and repost in one tap.",
             "ac": ["Users can save routes and re-post a prior parcel/trip in one tap",
                    "Repeat-booking entry points surfaced in the home hub"],
             "verify": "A returning user reposts a prior parcel in a single action."},
        ],
    },
    # =====================================================================
    # ===================  PRODUCTION-GRADE PHASE  ========================
    # =====================================================================
    {
        "code": "E13",
        "summary": "Release Engineering & Quality Gates",
        "status": "To Do",
        "context": "Move from deploy-from-laptop to a repeatable, safe pipeline: a real staging "
                   "environment, automated CD on merge, canary rollout with instant rollback, "
                   "end-to-end tests, and security scanning in CI — so releases are routine, not risky.",
        "ac": [
            "Changes flow main -> staging -> canary -> prod automatically with a one-click rollback.",
            "E2E happy paths and security scans gate every merge.",
        ],
        "children": [
            {"code": "E13-S1", "summary": "Staging environment (isolated Cloud Run + SQL + Firebase config)", "status": "To Do",
             "context": "A prod-like staging stack so changes are validated before real users see them.",
             "ac": ["Separate Cloud Run service + Cloud SQL (or schema) + Firebase config for staging",
                    "Staging uses test Stripe + AUDIT reCAPTCHA + seeded data"],
             "verify": "A change deployed to staging is reachable at a staging URL and isolated from prod."},
            {"code": "E13-S2", "summary": "Continuous deployment on merge (Cloud Build trigger)", "status": "To Do",
             "context": "Auto-build + deploy to staging on merge to main; promote to prod on approval/tag.",
             "ac": ["Cloud Build trigger builds, tests, and deploys on push to main",
                    "Migrations run automatically as a guarded step"],
             "verify": "Merging a PR deploys to staging with no manual gcloud commands."},
            {"code": "E13-S3", "summary": "Canary rollout + instant rollback (Cloud Run traffic split)", "status": "To Do",
             "context": "Shift a % of traffic to a new revision, watch error/latency, roll back in one step.",
             "ac": ["New revision gets N% traffic then ramps", "Rollback restores the prior revision instantly"],
             "verify": "A bad revision can be rolled back to the previous one in <1 min."},
            {"code": "E13-S4", "summary": "End-to-end test suite (web + native happy paths)", "status": "To Do",
             "context": "Playwright (web) + Maestro/Detox (native) covering sign-in -> post -> bid -> escrow.",
             "ac": ["E2E suite runs in CI against staging", "Core sender + traveller journeys covered"],
             "verify": "E2E suite passes in CI and fails on a regression."},
            {"code": "E13-S5", "summary": "Security scanning in CI (SAST + dependency/SCA)", "status": "To Do",
             "context": "Static analysis + dependency vulnerability scanning gate merges.",
             "ac": ["SAST (e.g. CodeQL) + SCA (npm audit / Dependabot) run on PRs",
                    "High-severity findings block merge; alerts on new CVEs"],
             "verify": "A known-vulnerable dependency fails the PR check."},
            {"code": "E13-S6", "summary": "Feature flags + remote config (kill switches)", "status": "To Do",
             "context": "Decouple deploy from release; safely ramp features and kill them without a redeploy.",
             "ac": ["Server + client read flags from a config service", "A flag can disable a feature live"],
             "verify": "Toggling a flag changes behaviour without a deploy."},
        ],
    },
    # =====================================================================
    {
        "code": "E14",
        "summary": "Trust, Safety & Fraud",
        "status": "To Do",
        "context": "A marketplace moving money and physical goods attracts fraud and abuse. Add scoring, "
                   "account-takeover defence, collusion/cap-gaming detection, content moderation, and "
                   "chargeback handling — protecting users, the platform, and the cost-sharing model.",
        "ac": [
            "Risky bookings/payments are scored and can be held or blocked.",
            "Collusion that games the cost-sharing cap is detectable.",
        ],
        "children": [
            {"code": "E14-S1", "summary": "Fraud scoring at booking/payment", "status": "To Do",
             "context": "Score on velocity, device, value, and sender/traveller mismatch signals.",
             "ac": ["A risk score is computed and recorded per booking/payment",
                    "High risk holds the action for review (not silently allowed)"],
             "verify": "A high-velocity test pattern is flagged/held."},
            {"code": "E14-S2", "summary": "Account-takeover protection", "status": "To Do",
             "context": "Detect anomalous sign-ins; re-auth before sensitive actions (payout details, payouts).",
             "ac": ["Anomalous-login signal captured", "Sensitive ops require recent re-auth"],
             "verify": "Changing payout details from a new device triggers re-auth."},
            {"code": "E14-S3", "summary": "Cap-gaming / collusion detection", "status": "To Do",
             "context": "Detect sender-traveller rings that repeatedly transact to disguise hire-and-reward.",
             "ac": ["Repeated same-pair bookings + frequency outliers surfaced to ops",
                    "Signals feed the compliance evidence trail"],
             "verify": "A synthetic collusion pattern is surfaced in the ops report."},
            {"code": "E14-S4", "summary": "Prohibited-item & content moderation", "status": "To Do",
             "context": "Image checks on parcel/handoff photos + a user report/flag flow.",
             "ac": ["Report flow on parcels/users", "Flagged content reaches ops; optional automated image screen"],
             "verify": "Reporting a parcel creates an ops case."},
            {"code": "E14-S5", "summary": "Chargeback handling + Stripe Radar", "status": "To Do",
             "context": "Wire Stripe Radar rules + handle dispute/chargeback webhooks end-to-end.",
             "ac": ["Radar enabled with sane rules", "Chargeback webhooks reconcile the booking + ledger"],
             "verify": "A test chargeback updates the booking and is recorded."},
        ],
    },
    # =====================================================================
    {
        "code": "E15",
        "summary": "Data, Analytics & Experimentation",
        "status": "To Do",
        "context": "Make decisions on data: an event pipeline into a warehouse, dashboards beyond the "
                   "pilot endpoint, and an A/B framework so growth and pricing changes are measured.",
        "ac": [
            "Product events land in a warehouse and power dashboards.",
            "Experiments can be run with proper assignment + analysis.",
        ],
        "children": [
            {"code": "E15-S1", "summary": "Event tracking (client + server)", "status": "To Do",
             "context": "Typed event SDK; privacy-aware; consent-gated (see E16).",
             "ac": ["Key funnel events emitted from app + API", "No PII in events without consent"],
             "verify": "A sign-up -> post -> match funnel is captured."},
            {"code": "E15-S2", "summary": "Warehouse + scheduled exports (BigQuery)", "status": "To Do",
             "context": "Stream/export events + Postgres snapshots into BigQuery for analysis.",
             "ac": ["Events + daily Postgres export land in BigQuery", "Scheduled + monitored"],
             "verify": "Yesterday's data is queryable in BigQuery."},
            {"code": "E15-S3", "summary": "Dashboards (liquidity / funnel / cohort / unit economics)", "status": "To Do",
             "context": "Looker Studio (or similar) on the warehouse for the team + investors.",
             "ac": ["Dashboards for liquidity, funnel, cohort retention, unit economics"],
             "verify": "Dashboards render correct numbers vs the pilot endpoint."},
            {"code": "E15-S4", "summary": "A/B experimentation framework", "status": "To Do",
             "context": "Deterministic assignment, exposure logging, and a readout method.",
             "ac": ["Users bucketed consistently; exposures logged", "An experiment can be analysed to significance"],
             "verify": "A toy experiment assigns + measures correctly."},
        ],
    },
    # =====================================================================
    {
        "code": "E16",
        "summary": "Privacy, Compliance & Legal Ops",
        "status": "To Do",
        "context": "UK GDPR + the cost-sharing legal posture require operational privacy: self-serve data "
                   "rights, retention automation, consent management, and scheduled regulator reporting — "
                   "extending the compliance-as-code firewall to data governance.",
        "ac": [
            "Users can export and delete their data; retention is enforced automatically.",
            "Regulator/insurer reports are produced on a schedule.",
        ],
        "children": [
            {"code": "E16-S1", "summary": "GDPR DSAR: self-serve data export + erasure", "status": "To Do",
             "context": "Right of access + right to erasure, preserving the immutable compliance audit per law.",
             "ac": ["User can request a full data export", "Account deletion erases personal data but retains lawful audit records"],
             "verify": "An export returns the user's data; deletion removes PII, keeps the audit chain."},
            {"code": "E16-S2", "summary": "Data retention automation", "status": "To Do",
             "context": "Purge data past its retention window; keep compliance/financial records as required.",
             "ac": ["Retention policy encoded + a scheduled purge job", "Compliance + financial records exempted"],
             "verify": "The purge removes expired non-essential data and nothing protected."},
            {"code": "E16-S3", "summary": "Consent management (cookies + analytics)", "status": "To Do",
             "context": "Web consent banner gating non-essential cookies/analytics; choice persisted + respected.",
             "ac": ["Decline-by-default banner; analytics fire only on consent"],
             "verify": "Declining consent stops non-essential tracking."},
            {"code": "E16-S4", "summary": "Records of processing + sub-processor register + DPA", "status": "To Do",
             "context": "Maintain the ROPA, sub-processor list (Stripe, Google, insurer), and DPAs.",
             "ac": ["ROPA + sub-processor register documented + kept current"],
             "verify": "Register lists every processor with purpose + safeguards."},
            {"code": "E16-S5", "summary": "Scheduled HMRC / Home Office / insurer reporting", "status": "To Do",
             "context": "Operationalise the E2-S10 exports on a schedule with delivery + retention.",
             "ac": ["Reports generated + retained on a cadence", "Coverage gaps alert"],
             "verify": "A scheduled run produces the correct period report."},
        ],
    },
    # =====================================================================
    {
        "code": "E17",
        "summary": "Scale & Reliability",
        "status": "To Do",
        "context": "Take the stack from pilot-sized to growth-ready: pooled connections + read replica, async "
                   "workers for retryable side effects, caching, an edge WAF/CDN, HA database, and cost "
                   "controls. Completes the Cloud Armor edge layer deferred from PBD-63.",
        "ac": [
            "The DB connection ceiling no longer bounds horizontal scale.",
            "Retryable work (push/email/payout) is queued and resilient; an edge WAF fronts the API.",
        ],
        "children": [
            {"code": "E17-S1", "summary": "Connection pooling + read replica", "status": "To Do",
             "context": "PgBouncer / connector tuning + a read replica so reads scale past db-f1-micro limits.",
             "ac": ["Pooled connections decouple instances from the raw connection cap",
                    "Heavy reads (corridors/matches) use a replica"],
             "verify": "Load test at higher instance counts holds without connection exhaustion (extends PBD-69)."},
            {"code": "E17-S2", "summary": "Async workers + queue (Cloud Tasks / Pub-Sub)", "status": "To Do",
             "context": "Move push/email/payout-retry off the request path with durable retries + idempotency.",
             "ac": ["Side effects enqueued + processed by a worker with retries", "Idempotent handlers"],
             "verify": "A transient downstream failure is retried to success, not lost."},
            {"code": "E17-S3", "summary": "Caching layer (Memorystore/Redis)", "status": "To Do",
             "context": "Cache hot, rarely-changing reads (corridor list, price bands).",
             "ac": ["Hot reads served from cache with sane TTL + invalidation"],
             "verify": "Corridor reads hit cache; invalidation works on change."},
            {"code": "E17-S4", "summary": "Edge WAF + CDN (Cloud Armor + HTTPS LB)", "status": "To Do",
             "context": "Front Cloud Run with an external HTTPS LB + Cloud Armor (the PBD-63 deferral).",
             "ac": ["Cloud Armor policy at the edge (rate/abuse/geo rules)", "Static/web assets via CDN"],
             "verify": "Edge blocks a flagged request before it reaches Cloud Run."},
            {"code": "E17-S5", "summary": "Cost monitoring + budget alerts + autoscaling tuning", "status": "To Do",
             "context": "Budgets + alerts so spend never surprises; right-size Cloud Run/SQL.",
             "ac": ["Budget + alert thresholds set", "Autoscaling/min-instances tuned from real traffic"],
             "verify": "Crossing a budget threshold alerts the team."},
            {"code": "E17-S6", "summary": "HA database + tested failover", "status": "To Do",
             "context": "Promote Cloud SQL to HA (regional) and rehearse failover.",
             "ac": ["HA enabled on the prod instance", "Failover tested with measured RTO"],
             "verify": "A simulated failover recovers within the RTO."},
        ],
    },
    # =====================================================================
    {
        "code": "E18",
        "summary": "Android Production Launch (Play Store)",
        "status": "To Do",
        "context": "A Play Store account is available, so the Android app can go to production: EAS release "
                   "builds + signing, Play Console listing + data-safety, closed testing, crash/ANR "
                   "monitoring, and a staged production rollout. (iOS App Store follows when an Apple "
                   "Developer account is set up.)",
        "ac": [
            "A signed Android App Bundle is built via EAS and uploaded to Play.",
            "Closed testing passes, then a staged production rollout with crash monitoring.",
        ],
        "children": [
            {"code": "E18-S1", "summary": "EAS release build + Android signing (AAB)", "status": "To Do",
             "context": "Use the eas.json production profile to build a signed App Bundle (EAS-managed keystore).",
             "ac": ["eas build --profile production --platform android produces an AAB",
                    "Signing keystore managed + recorded"],
             "verify": "An AAB artifact is produced and installs on a device.",
             "refs": ["app/eas.json"]},
            {"code": "E18-S2", "summary": "Play Console setup: listing, data safety, content rating, target API", "status": "To Do",
             "context": "Complete the Play listing, Data Safety form, content rating, and target-API requirements.",
             "ac": ["Store listing + Data Safety + content rating completed", "Meets Play target-API level"],
             "verify": "Play pre-launch validation passes."},
            {"code": "E18-S3", "summary": "Closed testing track + testers", "status": "To Do",
             "context": "Upload the AAB to closed testing; recruit the pilot testers.",
             "ac": ["AAB on closed testing", "Testers can install from Play"],
             "verify": "A tester installs the closed-testing build and completes a booking."},
            {"code": "E18-S4", "summary": "Crash/ANR monitoring (Crashlytics) + Play vitals", "status": "To Do",
             "context": "Wire Firebase Crashlytics + watch Android vitals (crash-free rate, ANRs).",
             "ac": ["Crashlytics reporting crashes/ANRs", "Vitals dashboard watched pre-release"],
             "verify": "A forced test crash appears in Crashlytics."},
            {"code": "E18-S5", "summary": "Staged production rollout + release process", "status": "To Do",
             "context": "Promote to production with a staged % rollout and a documented release/runbook.",
             "ac": ["Staged rollout (e.g. 10% -> 100%) with halt criteria", "Release process documented"],
             "verify": "Production release reaches users at a staged percentage."},
        ],
    },
    # =====================================================================
    {
        "code": "E19",
        "summary": "Customer Support & CX Ops",
        "status": "To Do",
        "context": "Production users need a way to get help and ops a way to act. Add support intake, an "
                   "expanded ops console for support actions, a knowledge base, and SLA/CSAT tracking.",
        "ac": [
            "Users can contact support in-app; ops can resolve common cases without DB access.",
        ],
        "children": [
            {"code": "E19-S1", "summary": "Support intake (in-app contact + helpdesk)", "status": "To Do",
             "context": "In-app 'Contact support' routed to a helpdesk inbox with booking context attached.",
             "ac": ["In-app support entry point", "Tickets land in a helpdesk with context"],
             "verify": "Submitting a support request creates a ticket with the booking ref."},
            {"code": "E19-S2", "summary": "Ops console v2: support actions", "status": "To Do",
             "context": "Lookups + safe actions (resend hand-off codes, refund, adjust booking) for support.",
             "ac": ["Support can look up a user/booking and take guarded actions", "Every action audited"],
             "verify": "A support agent resolves a resend-code case end-to-end."},
            {"code": "E19-S3", "summary": "Knowledge base / FAQ", "status": "To Do",
             "context": "Self-serve help content (how cost-sharing works, prohibited items, hand-off).",
             "ac": ["Published, searchable FAQ linked from the app", "Framing-clean"],
             "verify": "FAQ is reachable and answers the top pilot questions."},
            {"code": "E19-S4", "summary": "SLA + CSAT tracking", "status": "To Do",
             "context": "Track first-response/resolution SLAs and post-resolution CSAT.",
             "ac": ["SLA timers + CSAT survey on resolved tickets"],
             "verify": "A resolved ticket records response time + a CSAT score."},
        ],
    },
    # =====================================================================
    {
        "code": "E20",
        "summary": "Consumer-grade Flow UX (Uber / BlaBlaCar / DPD level)",
        "status": "In Progress",
        "context": "The screens are functional but bare. Rebuild the core journeys into guided, "
                   "map-aware, polished flows that feel like Uber/BlaBlaCar/DPD: a real design "
                   "system, step-by-step sender/traveller wizards, live tracking with a status "
                   "timeline + map, and consistent empty/loading/error states. No store submission "
                   "until the flows feel production-quality.",
        "ac": [
            "Sender and traveller journeys are guided, validated, multi-step flows (not raw forms).",
            "Live tracking shows a status timeline + map; states/loading/errors are consistent.",
            "A shared design system backs every screen.",
        ],
        "children": [
            {"code": "E20-S1", "summary": "Design system kit v2 (pills, stepper, cards, sheet, states)", "status": "Done",
             "context": "Reusable atoms/molecules: status pills, progress stepper, list/section cards, bottom "
                        "sheet, money/price display, avatars, empty states, loading skeletons, toasts.",
             "ac": ["Shared components used across screens", "Airbnb palette + glass styling consistent"],
             "verify": "Screens render from the shared kit; no bespoke one-off styles per screen.",
             "refs": ["app/src/components/ui.tsx", "app/src/theme.ts"]},
            {"code": "E20-S2", "summary": "Sender flow: guided 'Send a parcel' wizard", "status": "In Review",
             "context": "Route -> pickup/dropoff (map) -> parcel size/value -> contribution (cost-sharing framed) "
                        "-> review & confirm, with a progress stepper + per-step validation.",
             "ac": ["Multi-step wizard with progress + back/next", "Per-step validation; clear review screen",
                    "Contribution framed as cost-sharing (framing-clean)"],
             "verify": "Walk the wizard end-to-end; a parcel is posted with correct data."},
            {"code": "E20-S3", "summary": "Sender: ranked bids review + accept + escrow fund", "status": "In Review",
             "context": "Traveller bid cards (trust score, rating, ETA, transport, contribution) ranked; accept -> "
                        "fund escrow with a clear price breakdown.",
             "ac": ["Ranked bid cards with trust/ETA/price", "Accept + fund with itemised breakdown"],
             "verify": "Accept a bid and fund; booking advances."},
            {"code": "E20-S4", "summary": "Live tracking screen (status timeline + map + hand-off)", "status": "In Review",
             "context": "Booking detail as a tracking view: status timeline, map, participant info, hand-off "
                        "codes, live updates (Firestore mirror + poll).",
             "ac": ["Status timeline reflects lifecycle", "Map + participant + hand-off codes shown live"],
             "verify": "A status change updates the timeline live."},
            {"code": "E20-S5", "summary": "Traveller flow: post trip + map-first parcel discovery", "status": "In Review",
             "context": "Guided trip post + a map/list of matchable parcels on the route with contribution, "
                        "detour, and trust; one-tap bid.",
             "ac": ["Trip post wizard", "Map/list discovery of cap-valid parcels; one-tap bid"],
             "verify": "Post a trip, discover a parcel, place a bid."},
            {"code": "E20-S6", "summary": "Onboarding + empty/loading/error states", "status": "In Review",
             "context": "First-run explainer (send vs carry, how cost-sharing works) + consistent empty states, "
                        "skeleton loaders, and error toasts across the app.",
             "ac": ["First-run intro", "Every list/screen has empty + loading + error states"],
             "verify": "Fresh account sees onboarding; lists show skeletons then content/empty."},
            {"code": "E20-S7", "summary": "Public landing page (browse-first, no login)", "status": "In Review",
             "context": "Like BlaBlaCar/Uber: don't force login to look. A public landing with the value prop, "
                        "how cost-sharing works, live corridors, and clear CTAs — reachable with no account.",
             "ac": ["Unauthenticated users see a landing page, NOT a forced sign-in",
                    "Hero + how-it-works + live corridors + CTAs to send/carry",
                    "Signed-in users go straight to the home hub"],
             "verify": "Open the app logged out -> landing renders; logged in -> home.",
             "refs": ["app/app/index.tsx"]},
            {"code": "E20-S8", "summary": "Public browse + contribution estimator (no login)", "status": "In Review",
             "context": "Let visitors see supply and estimate price before signing up: public corridor list + a "
                        "size/route -> suggested contribution estimator.",
             "ac": ["GET /corridors + /price-suggestion are public", "Estimator returns a capped suggestion with no auth"],
             "verify": "Logged out, pick a route + size -> see an estimated contribution.",
             "refs": ["api/src/routes/trips.ts", "api/src/routes/pricing.ts"]},
            {"code": "E20-S9", "summary": "Auth-gate at commitment (sign in to post/bid/pay)", "status": "In Review",
             "context": "Authenticate only when it creates an obligation / moves money / reveals PII. Browse + start "
                        "the wizard anonymously; require sign-in at the final Post/Bid/Fund step.",
             "ac": ["Wizards load + run without auth (corridors fetched publicly)",
                    "The commit action redirects to sign-in when logged out, money/PII stay gated + KYC"],
             "verify": "Logged out, walk the send-a-parcel wizard; Post prompts sign-in."},
        ],
    },
    # =====================================================================
    {
        "code": "E21",
        "summary": "Legal-aligned model & positioning v2 (counsel-gated)",
        "status": "In Progress",
        "context": "Encode the final legal/positioning strategy. The two existential risks are worker "
                   "classification and Right-to-Work; licensing is light; marketing language is itself a "
                   "compliance tool. Several items reverse load-bearing mechanics and MUST have a UK "
                   "solicitor's sign-off before shipping — those are flagged counsel-gated.",
        "ac": [
            "User-facing language never sounds like a courier/logistics company (enforced).",
            "Classification + RTW posture matches counsel's structure before launch.",
        ],
        "children": [
            {"code": "E21-S1", "summary": "Marketing guardrail lint (never-say terms) across app + api", "status": "In Review",
             "context": "Extend the framing lint to fail CI on courier/logistics/labour/carriage language "
                        "(our couriers, delivery fleet, we deliver, become a driver, deliver by train, "
                        "guaranteed delivery, fully insured) in BOTH api and app copy. Market the connection "
                        "and the journey, never the labour or the carriage.",
             "ac": ["Lint scans app/ + api/src", "Dangerous affirmative phrasing fails CI; legit negations pass"],
             "verify": "node api/scripts/banned-words.mjs flags 'our couriers' but not 'never a courier fee'.",
             "refs": ["api/scripts/banned-words.mjs"]},
            {"code": "E21-S2", "summary": "Copy pass: align all strings to the say/never-say list", "status": "To Do",
             "context": "Marketplace/connection/journey framing; buddy copy emphasises autonomy ('you choose what, "
                        "when, how'); soften any labour framing (e.g. bare 'Carry & earn').",
             "ac": ["Sender, buddy, operator copy follow the positioning doc", "Passes the guardrail lint"],
             "verify": "Copy review against the say/never-say list passes."},
            {"code": "E21-S3", "summary": "Sealed-package + sender declaration + right-to-refuse (replace open-box)", "status": "In Review",
             "context": "COUNSEL-GATED. Inspection gives the carrier knowledge and erodes the innocent-carrier "
                        "defence; the sealed + declared + right-to-refuse model is safer. Reverses E2-S8.",
             "ac": ["Pickup no longer requires an open-box inspection", "Sender contents declaration + carrier right-to-refuse recorded"],
             "verify": "Solicitor signs off; pickup flow updated + audited."},
            {"code": "E21-S4", "summary": "Right-to-Work for ALL buddies at onboarding + substitute re-check", "status": "In Review",
             "context": "COUNSEL-GATED. 2026 platform regime is courier-targeted, platform-liable (£60k/worker + "
                        "criminal). Verify every carrier, not just Pro; re-check substitutes (the substitution "
                        "right is exactly what the Home Office polices).",
             "ac": ["RTW required to carry at all (not Pro-only)", "Substitution triggers a fresh RTW check"],
             "verify": "Solicitor signs off; onboarding gates carrying on RTW for all buddies."},
            {"code": "E21-S5", "summary": "Self-employment-in-substance controls", "status": "To Do",
             "context": "COUNSEL-GATED. Genuine substitution right, no imposed pricing, no obligation to accept, "
                        "no control over how/when they travel, no punitive deactivation. Note: full-time-only "
                        "framing works AGAINST classification — favour supplementary, going-anyway carriers.",
             "ac": ["Platform mechanics reviewed against worker-status tests with counsel"],
             "verify": "Counsel pressure-tests the classification structure; gaps closed."},
            {"code": "E21-S6", "summary": "Two-layer liability terms + optional sender-paid insurance bolt-on", "status": "In Review",
             "context": "COUNSEL-GATED. CRA-safe terms (can't fully exclude own-negligence) + a separate "
                        "discretionary goodwill layer (Uber's structure). Make cover an OPTIONAL sender bolt-on, "
                        "not mandatory; never market 'fully insured'.",
             "ac": ["Solicitor-drafted two-layer liability", "Insurance optional at checkout, not forced"],
             "verify": "Terms reviewed; checkout offers optional cover."},
            {"code": "E21-S7", "summary": "Quantified, substantiated green claims (CO2 vs van)", "status": "To Do",
             "context": "ASA/CMA Green Claims Code: accurate, substantiated, not misleading. Surface a defensible "
                        "per-delivery avoided-CO2 figure (vs a dedicated van), 'fewer vans' as the lead message — "
                        "positioning, never a compliance argument.",
             "ac": ["Methodology documented", "Per-delivery avoided-CO2 shown with an honest van comparison"],
             "verify": "A reviewer can reproduce the CO2 figure from the methodology."},
            {"code": "E21-S8", "summary": "No international students as carriers (broaden the lock)", "status": "In Review",
             "context": "COUNSEL-GATED. Extend the student restriction from Pro-only to carrying at all — only "
                        "people who can lawfully do this carry. Removes the contested 'going anyway' parcel defence.",
             "ac": ["Student-visa users cannot carry on any tier"],
             "verify": "Counsel signs off; carry path blocks student-visa users."},
            {"code": "E21-S9", "summary": "Operator + government positioning kit (pilot pitch)", "status": "To Do",
             "context": "Revenue-first to operators ('monetise spare capacity, hit decarbonisation targets'), "
                        "innovation/net-zero to government. A regional/open-access rail or coach pilot sanctions "
                        "the carriage and dissolves conditions-of-carriage risk — pursue as upside, not launch-gating.",
             "ac": ["Operator + government one-pagers", "Pilot outreach list"],
             "verify": "Positioning kit drafted; first operator approached."},
        ],
    },
]
